CREATE TABLE colors (color INTEGER PRIMARY KEY, description TEXT);
INSERT INTO colors (color, description) VALUES (-3,'a');
INSERT INTO colors (color, description) VALUES (-2,'b');
INSERT INTO colors (color, description) VALUES (-1,'a');
INSERT INTO colors (color, description) VALUES (0,'c');
INSERT INTO colors (color, description) VALUES (1,'d');
INSERT INTO colors (color, description) VALUES (2,'e');
INSERT INTO colors (color, description) VALUES (3,'f');
INSERT INTO colors (color, description) VALUES (4,'g');
INSERT INTO colors (color, description) VALUES (5,'h');
INSERT INTO colors (color, description) VALUES (6,'i');
INSERT INTO colors (color, description) VALUES (7,'j');
INSERT INTO colors (color, description) VALUES (8,'k');
INSERT INTO colors (color, description) VALUES (9,'l');
INSERT INTO colors (color, description) VALUES (10,'m');
